# Generated by Django 4.2.1 on 2023-12-02 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.BigIntegerField(default=0)),
                ('host', models.CharField(default='', max_length=1000)),
                ('end_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('cost_per_unit', models.IntegerField()),
                ('unit_name', models.CharField(max_length=100)),
                ('sourced_country', models.CharField(max_length=100)),
                ('warehouse_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('confirmed_item', models.BooleanField()),
                ('user_added', models.CharField(max_length=1000)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.basket')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.product')),
            ],
        ),
    ]
