# Generated by Django 4.2.1 on 2023-12-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='co2_saved',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
