# Generated by Django 4.2.1 on 2023-12-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_product_co2_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='co2_saved',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
