# Generated by Django 4.2.1 on 2023-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_basketitem_cost_alter_product_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
